### ISSUE TITLE
Upload a Photo

### ISSUE THREAD

**Issue by leblancexplores** [spacesuitdiver/meowtch-maker#16]
## Upload a Photo
As a user, I want to be able to take a photo with my webcam so that I can be presented with pets to adopt at random when I am indecisive.

## Acceptance Criteria
- [ ] preview.html with a preview of the webcam
- [ ] preview.html that has a cachink! button
- [ ] cachink! button that captures the user's photo
- [ ] cachink! button that uploads the photo to api for comparison

## Subtasks
- [ ] Create the preview.html #17
